// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Sirac Ozmen
//
// Generated by tools/near_field_table.py; do not edit. The rigid
// sphere's variation in dB, exactly, for a set measured at 1.2 m and a
// head of 8.75 cm: per point, the incidence angle, the distance in
// metres, then the variation at each frequency.

// clang-format off
#define REFERENCE_POINTS 7
#define REFERENCE_FREQUENCIES 7

static const double s_referenceHz[REFERENCE_FREQUENCIES] = {
    100.0, 300.0, 1000.0, 3000.0, 6000.0, 10000.0, 12000.0,
};

static const double s_reference[REFERENCE_POINTS][2 + REFERENCE_FREQUENCIES] = {
    {0.0, 0.150, 9.3814, 9.0261, 7.3724, 6.8942, 6.8335, 6.8861, 6.9005},
    {30.0, 0.200, 4.2811, 4.0804, 2.9720, 2.6637, 2.7176, 2.8043, 2.8319},
    {62.5, 0.900, 0.1247, 0.1175, 0.0373, 0.0162, 0.0106, 0.0091, 0.0094},
    {85.0, 0.120, -2.7152, -2.7979, -4.0962, -5.7665, -7.4039, -8.9344, -9.5605},
    {97.5, 0.300, -0.8836, -0.9074, -1.3546, -1.9228, -2.4320, -2.9274, -3.1368},
    {135.0, 0.110, -6.6821, -6.7605, -7.2378, -9.1728, -11.0337, -12.8077, -13.5326},
    {180.0, 0.500, -1.2258, -1.2283, -1.2413, -1.3738, -1.5621, -1.7608, -1.8449},
};
// clang-format on
